wafflestudio/snutt-frontend

- friends/App.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1688553182691769
> ✨ 토큰 받아서 prop으로

- friends/src/main.tsx
applied https://wafflestudio.slack.com/archives/C0PAVPS5T/p1689417215537049?thread_ts=1688553182.691769&cid=C0PAVPS5T
> ✨ 토큰 등 키값 변경, 추가 프로퍼티들 타입으로 정의

- friends/src/clients/apiClient.ts
- friends/src/entities/courseBook.ts
- friends/src/entities/friend.ts
- friends/src/entities/semester.ts
- friends/src/entities/time.ts
- friends/src/entities/user.ts
- friends/src/entities/year.ts
- friends/src/infrastructures/createFetchClient.ts
- friends/src/infrastructures/createFriendRepository.ts
- friends/src/infrastructures/createFriendService.ts
- friends/src/main.tsx
- friends/src/repositories/friendRepository.ts
- friends/src/usecases/friendService.ts
applied:
- https://github.com/wafflestudio/snutt-timetable/pull/141
- https://github.com/wafflestudio/snutt-timetable/pull/139
> 👽 친구 관련 api들 추가

- friends/src/app/screens/MainScreen/FriendTimetable/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/api-aba7976344b741c5b5bcfd5191363bfa?pvs=4
> ✨ 학기 여러개 중에 선택할 수 있도록

- friends/src/app/components/Button.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentRequestedList/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/index.tsx
- friends/src/infrastructures/createFriendService.ts
- friends/src/usecases/friendService.ts
> ✨ Drawer 영역 스타일 관련 기능 구현 (1)

- friends/src/app/components/Input.tsx
- friends/src/app/screens/MainScreen/index.tsx
> 💄 메인화면 바텀시트 내 콘텐츠 스타일 조정

- friends/src/app/assets/close.svg
- friends/src/app/assets/snutt-logo.svg
- friends/src/app/components/BottomSheet.tsx
- friends/src/app/components/Icons/CloseIcon.tsx
- friends/src/app/components/Icons/SnuttLogoIcon.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
- friends/src/infrastructures/createFriendService.ts
- friends/src/usecases/friendService.ts
https://www.notion.so/wafflestudio/drawer-10668b88634146278502ca2204a2547f?pvs=4
> 💄 drawer 영역 마크업 처리

- friends/src/app/assets/user-plus.svg
- friends/src/app/components/Timetable.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/89be0c14bf744b41aa2f7cc1acfd94ef?pvs=4
> ✨ 사이드바 친구 추가하기 버튼 구현

- friends/src/app/queries/useFriendCourseBooks.ts
- friends/src/app/screens/MainScreen/FriendTimetable/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
- friends/src/infrastructures/createFriendRepository.ts
- friends/src/infrastructures/createFriendService.ts
- friends/src/repositories/friendRepository.ts
- friends/src/usecases/friendService.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1692441318309649?thread_ts=1691206392.965919&cid=C0PAVPS5T
courseBook도 coursebook으로 바꾸면 좋긴 할텐데 프론트는 전부가 courseBook 으로 쓰고 있어서 나중에 생각
> 👽 registered-course-books -> coursebooks

- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/52344a7afcb140c4b76cedebc5ad4faf?pvs=4
> 💄 사이드바 열 때 메인화면은 옆으로 안 밀리도록

- friends/src/app/components/Timetable.tsx
- friends/src/app/contexts/ServiceContext.ts
- friends/src/app/queries/useColors.ts
- friends/src/app/queries/useFriendCourseBooks.ts
- friends/src/app/queries/useFriendPrimaryTable.ts
- friends/src/app/queries/useFriends.ts
- friends/src/app/screens/MainScreen/FriendTimetable/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentRequestedList/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
- friends/src/main.tsx
> ♻️ context 별도 파일로 분리

- friends/package.json
- friends/src/app/components/Appbar.tsx
- friends/src/app/components/BottomSheet.tsx
- friends/src/app/components/Paper.tsx
- friends/src/app/components/Select.tsx
- friends/src/app/contexts/ThemeContext.ts
- friends/src/app/screens/MainScreen/FriendTimetable/FriendGuide/index.tsx
- friends/src/app/screens/MainScreen/FriendTimetable/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
- friends/src/app/styles/colors.ts
- friends/src/app/styles/theme.ts
- friends/src/infrastructures/createCourseBookService.ts
- friends/src/infrastructures/createTimetableViewService.ts
- friends/src/main.tsx
- friends/yarn.lock
[SQ-9](https://www.notion.so/wafflestudio/a98875221a514408926ef0a9b39625d0?pvs=4)도 같이 고쳐졌습니다
> ✨ 배경색에 다크모드 적용

- friends/src/main.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1692498282986259?thread_ts=1692498022.594299&cid=C0PAVPS5T
> ⚰️ 다크모드 디폴트값 제거

- friends/src/app/components/Select.tsx
fixed https://www.notion.so/wafflestudio/ab7b7e1a39b94930b1224ef72d70fbab?pvs=4
> 💄 셀렉박스 최대높이 지정

- friends/src/app/components/Select.tsx
- friends/src/app/screens/MainScreen/FriendTimetable/index.tsx
- friends/src/infrastructures/createCourseBookService.ts
- friends/src/usecases/courseBookService.ts
fixed https://www.notion.so/wafflestudio/nnnn-n-6367b6bef4fe4931b561c97f253b4d49?pvs=4
> ✨ coursebook 포맷 통일

- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/index.tsx
https://www.notion.so/wafflestudio/918aad27fbd84d82a1caa1cf36ca86e1?pvs=4
> ✨ 친구 변경 시 사이드바 닫힘

- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/valid-f61c5fb1a9c9491c8bfeba87acd142bb?pvs=4
> 🩹 닉네임 valid해졌을 때 안내메세지 자리는 유지되도록

- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/2584f882166b4ec1bc4a11518f204c2d?pvs=4
> ✨ 친구 요청 전송 후 얼럿

- friends/src/app/components/Button.tsx
- friends/src/app/components/Input.tsx
- friends/src/app/components/Timetable.tsx
- friends/src/app/components/Typography.tsx
- friends/src/app/contexts/TextContext.ts
- friends/src/main.tsx
https://www.notion.so/wafflestudio/35ecdaf106b948e7a4be496c073b62fe?pvs=4
> ✨ 유동/고정 폰트 지원

- friends/src/app/components/BottomSheet.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1692890728602389
알려진 버그라서 알려진 해결방법으로 해결합니다.
> 🩹 바텀시트 글리치 임시 픽스

- friends/src/app/App.tsx
- friends/src/app/components/Appbar.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1692679644594519
> 🩹 SafeAreaView 적용

- friends/package.json
- friends/yarn.lock
https://www.notion.so/wafflestudio/RN-0-72-0-0-72-3-287a593e11964c75836c5c4223f8a90f?pvs=4
> ⬆️ upgrade react native 0.72.0 -> 0.72.3

- friends/src/app/components/Input.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/9d3a88e099814b668a93aa8c820a510f?pvs=4
> 🚸 바텀시트 열면 인풋 자동 포커스

- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/index.tsx
- friends/src/app/styles/theme.ts
https://www.notion.so/7e3f69c06c814cb0bbe20bde354148af?d=155f91e6a71b45a9bc5d168b029a039f&pvs=4
> 💄 탭스 텍스트 색 다크모드 적용

- friends/src/app/components/EmptyView.tsx
- friends/src/app/screens/MainScreen/FriendTimetable/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentRequestedList/index.tsx
https://www.notion.so/wafflestudio/eab52db3be954c17b5b30545ad9db011?pvs=4
> 친구에게 시간표 하나도 없는 케이스 대응

- friends/src/app/App.tsx
fixed https://www.notion.so/wafflestudio/8daf19b5d8cb44d8b015c4a1ee00542b?pvs=4
> 🩹 navigation container 기본 배경

- friends/src/app/screens/MainScreen/FriendTimetable/FriendGuide/index.tsx
> 💄 자세히 보기 버튼 폰트 사이즈 수정

- friends/src/app/components/Carousel.tsx
[되나?](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1693967640624969)
> 🚸 캐러샐 사용성 개선

- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
fixed https://www.notion.so/wafflestudio/alert-c8d1a842dc9847608f226be0e484cd16?pvs=4
> 🩹 친구 이름 유효하지 않을때 alert

- friends/src/app/assets/icons/hamburger.svg
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1694008871868869
> 🍱 햄버거 아이콘 변경

- friends/src/app/components/Carousel.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1694139970890649
> 🚸 캐러샐 한번에 스와이프로 한개만 이동 가능하도록

- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
resolved https://www.notion.so/wafflestudio/alert-button-destructive-4431e5f85e4049acbe81f29a9361ba01?pvs=4
> 💄 삭제 alert 삭제 버튼 스타일 destructive

- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/7f4322d25cc541428ba9319a8ce61b0c?pvs=4
> 💄 바텀시트 가이드문구 크기, 간격 수정

- friends/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- friends/src/app/screens/MainScreen/index.tsx
https://www.notion.so/wafflestudio/d1b63924404e424197258be19368f32d?pvs=4
추가로, 삭제된 친구의 시간표 invalidate 하려다가 404때리는것도 같이 고칩니다.
> 🩹 친구 삭제 시 버그 픽스

- .github/workflows/deploy-friends-prod.yml
- README.md
> ✏️ fix repo name

- apps/friends-react-native/src/infrastructures/createTimetableViewService.ts
- apps/friends-react-native/src/usecases/timetableViewService.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1694486580919129?thread_ts=1694484026.820409&cid=C0PAVPS5T
기존: 8시 ~ 22시 (심지어 버그있었음 😶‍🌫️ 왜 ceil로 해놨지..)
변경: 9시 ~ 18시
> 👽 시간표 자동조정 로직 클라랑 통일 및 종료시간 버그 수정

- apps/friends-react-native/src/app/screens/MainScreen/index.tsx
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1694491883994319?thread_ts=1694487802.190859&cid=C0PAVPS5T
> 💄 drawer 너비 픽스

- apps/friends-react-native/package.json
- apps/friends-react-native/src/app/queries/useColors.ts
- apps/friends-react-native/src/app/queries/useFriendCourseBooks.ts
- apps/friends-react-native/src/app/queries/useFriendPrimaryTable.ts
- apps/friends-react-native/src/app/queries/useFriends.ts
- apps/friends-react-native/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentActiveList/index.tsx
- apps/friends-react-native/src/app/screens/MainScreen/ManageFriendsDrawerContent/ManageFriendsDrawerContentRequestedList/index.tsx
- apps/friends-react-native/src/app/screens/MainScreen/index.tsx
- yarn.lock
migration guide: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5
> ⬆️ react-query v5 버전업

- apps/friends-react-native/src/app/components/Timetable.tsx
https://www.notion.so/wafflestudio/20c9fa4e43ce4bdeb54de5a16b881ed5?pvs=4
강의실이 없는 경우 강의실 자리를 비워줍니다.
보니까 혁신의과학 특 가운데에있는 친구가 `' '` 가 내려오는 것 같아서.. trim 까지 해줘야될듯 😮‍💨
> 💄 강의실이 없는 경우 중앙정렬

- apps/friends-react-native/package.json
- apps/friends-react-native/src/app/components/Timetable.tsx
- apps/friends-react-native/src/app/contexts/FeatureContext.ts
- apps/friends-react-native/src/app/screens/MainScreen/index.tsx
- apps/friends-react-native/src/entities/feature.ts
- apps/friends-react-native/src/main.tsx
- yarn.lock
draft: https://wafflestudio.slack.com/archives/C0PAVPS5T/p1701444940211509
> ✨ 마지막으로 본 친구 저장

- .github/CODEOWNDERS
> :busts_in_silhouette: codeowner 픽스

- apps/friends-react-native/package.json
- apps/snutt-ev-web-v2/package.json
- apps/snutt-ev-web-v2/src/app/(routes)/main/page.tsx
- apps/snutt-ev-web-v2/src/app/_components/AppBar/AppBarTitle/index.module.css
- apps/snutt-ev-web-v2/src/app/_components/AppBar/AppBarTitle/index.tsx
- apps/snutt-ev-web-v2/src/app/_components/AppBar/index.module.css
- apps/snutt-ev-web-v2/src/app/_components/AppBar/index.tsx
- apps/snutt-ev-web-v2/src/app/_pages/MainPage/index.tsx
- yarn.lock
async 컴포넌트에 대한 타입 지원을 위해 typescript, @tyeps/react-dom 버전을 올렸습니다. friends 쪽에서도 버전 통일하면 좋을 것 같은데 이건 이후 PR에서 진행하겠습니다.
마크업은 완성은 아니고 일단 적당히만 했습니다.
> ✨ 메인화면 앱바 자리 잡기

- .github/workflows/deploy-friends-react-native-dev.yml
- .github/workflows/deploy-friends-react-native-prod.yml
- apps/friends-react-native/scripts/deploy.sh
> 🧑‍💻 친구기능 배포 태그 friends- -> friends-react-native- 로 변경

- apps/snutt-ev-webview/src/app/utils/getServerServices.ts
- apps/snutt-ev-webview/src/entities/Evaluation.ts
- apps/snutt-ev-webview/src/infrastructures/createEvaluationService.ts
- apps/snutt-ev-webview/src/infrastructures/createEvalutionRepository.ts
- apps/snutt-ev-webview/src/repositories/EvaluationRepository.ts
- apps/snutt-ev-webview/src/usecases/EvaluationService.ts
- apps/snutt-ev-webview/src/utils/Pagination.ts
> 강의평 타입 추가/api 연동

- apps/snutt-ev-webview/src/clients/HttpClient.ts
- apps/snutt-ev-webview/src/infrastructures/createFetchClient.ts
- apps/snutt-ev-webview/src/utils/object.ts
- snakeToCamel fetchClient에 적용
> snakeToCamel fetchClient에 적용

- apps/snutt-webclient/src/components/icons/ic-friend.tsx
- apps/snutt-webclient/src/components/layout/layout-notification/layout-notification-popover-content/index.tsx
- apps/snutt-webclient/src/entities/notification.ts
- apps/snutt-webclient/src/infrastructures/implNotificationSnuttApiRepository.ts
- apps/snutt-webclient/src/mocks/fixtures/notification.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1716361798339349?thread_ts=1716291778.118299&cid=C0PAVPS5T
> ✨ 알림 타입 5,6 대응

- apps/snutt-webclient/src/entities/lecture.ts
- packages/snutt-api/src/apis/snutt-timetable/schemas.ts
> 👽 snu4t schema 일괄 추가

- apps/snutt-webclient/e2e/main/lecture-section.spec.ts
- apps/snutt-webclient/playwright.config.ts
- apps/snutt-webclient/src/mocks/fixtures/bookmark.ts
- apps/snutt-webclient/src/mocks/handlers/index.ts
- apps/snutt-webclient/src/pages/main/main-lecture-section/common/main-lecture-listitem/index.component.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-section/common/main-lecture-listitem/index.presenter.ts
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1716724965976609?thread_ts=1716399538.928789&cid=C0PAVPS5T
> :adhesive_bandage: 관심강좌 제거 시 모달 안 닫히는 이슈 픽스

- apps/snutt-webclient/src/App.tsx
- apps/snutt-webclient/src/pages/loading/index.tsx
- apps/snutt-webclient/src/pages/main/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-create-dialog/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-edit-dialog/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-edit-dialog/main-lecture-delete-dialog/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-section/common/main-lecture-listitem/index.presenter.ts
- apps/snutt-webclient/src/pages/main/main-lecture-section/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-section/main-bookmark-lecture-tab/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-section/main-current-lecture-tab/index.tsx
- apps/snutt-webclient/src/pages/main/main-lecture-section/main-search-lecture-tab/index.tsx
- apps/snutt-webclient/src/pages/main/main-searchbar/index.tsx
- apps/snutt-webclient/src/pages/main/main-timetable-section/index.tsx
- apps/snutt-webclient/src/pages/main/main-timetable-section/main-delete-timetable-dialog/index.tsx
- apps/snutt-webclient/src/pages/main/main-timetable-section/main-rename-timetable-dialog/index.tsx
- apps/snutt-webclient/src/usecases/timeMaskService.ts
> :recycle: 상태 설계 개선

- apps/friends-react-native/src/app/screens/MainScreen/index.tsx
- apps/friends-react-native/src/repositories/responses/Friend.ts
> [friends-native] 오타 수정
